################
### Language ###
################
language: java

###########
### JDK ###
###########
jdk:
  - oraclejdk11

#####################
### Notifications ###
#####################
notifications:
  email: false

####################
### Build script ###
####################
script:
  - mvn clean compile package
